export const authors: string[] = [
  'A. Robert',
  'Agustin de Hipona',
  'Alfredo Saenz',
  'Brant Pitre',
  'Eusebio de Cesarea',
  'F. F. Bruce',
  'GIUSEPPE ALBERIGO',
  'Herculano Alves',
  'Iglesia Catolica',
  'Joel Peters',
  'Josh McDowell',
  'Lee Martin McDonald',
  'Miguel Ángel Tabet',
  'Robert A. Sungenis, Ph.D',
  'Scott Hahn',
  'TRENT HORN',
  'Javier Olivera Ravasi',
  'Fr. John J. Pasquini',
  'Martin Lutero',
  'Cristián Rodrigo Iturralde',
  'ApologeticaCatolica.org',
  'J. B. Carol',
  'Justino Mártir',
  'John Lennox',
];

export const categories: string[] = [
  'Amor',
  'Canon Bíblico',
  'Catecismo',
  'Concilios',
  'Conversiones',
  'Eucaristia',
  'Historia de la Iglesia',
  'Jesucristo',
  'Justificación',
  'María',
  'Misa',
  'Padres de la Iglesia',
  'Sola Escritura',
  'Temas Variados',
  'Bíblia General',
  'Protestantismo',
  'Curso',
  'Fe y Razon'
];
